package com.salvadordetexto.app;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

public class AppUi {
    final Activity a;
    final int G=Color.rgb(15,92,74), G2=Color.rgb(43,128,104), BG=Color.rgb(247,249,246), SOFT=Color.rgb(229,241,236), TEXT=Color.rgb(23,53,45), MUTED=Color.rgb(105,125,117);
    int step=1;
    AppUi(Activity a){this.a=a;a.getWindow().setStatusBarColor(G);a.getWindow().setNavigationBarColor(Color.WHITE);}
    int d(int v){return(int)(v*a.getResources().getDisplayMetrics().density+.5f);}
    GradientDrawable sh(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(d(r));return g;}
    TextView t(String s,int z,boolean b){TextView v=new TextView(a);v.setText(s);v.setTextColor(TEXT);v.setTextSize(z);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setPadding(0,d(4),0,d(4));return v;}
    TextView m(String s){TextView v=t(s,14,false);v.setTextColor(MUTED);return v;}
    LinearLayout page(String title,String sub){LinearLayout p=new LinearLayout(a);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(d(20),d(22),d(20),d(24));p.setBackgroundColor(BG);p.addView(t(title,28,true));if(sub!=null)p.addView(m(sub));return p;}
    LinearLayout card(){LinearLayout c=new LinearLayout(a);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(d(17),d(16),d(17),d(16));c.setBackground(sh(Color.WHITE,22));LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-1,-2);x.setMargins(0,d(10),0,0);c.setLayoutParams(x);return c;}
    Button b(String s,View.OnClickListener l){Button x=new Button(a);x.setText(s);x.setAllCaps(false);x.setTextColor(Color.WHITE);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setBackground(sh(G,16));x.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,d(52));p.setMargins(0,d(9),0,0);x.setLayoutParams(p);return x;}
    Button alt(String s,View.OnClickListener l){Button x=b(s,l);x.setTextColor(G);x.setBackground(sh(SOFT,16));return x;}
    EditText f(String hint,boolean multi){EditText e=new EditText(a);e.setHint(hint);e.setTextColor(TEXT);e.setHintTextColor(Color.rgb(145,160,154));e.setBackground(sh(Color.WHITE,16));e.setPadding(d(14),d(12),d(14),d(12));if(multi)e.setMinLines(4);else e.setSingleLine();LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,d(8),0,0);e.setLayoutParams(p);return e;}
    void show(LinearLayout p){ScrollView s=new ScrollView(a);s.setFillViewport(true);s.addView(p);LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav());a.setContentView(root);}
    LinearLayout nav(){LinearLayout n=new LinearLayout(a);n.setOrientation(LinearLayout.HORIZONTAL);n.setBackgroundColor(Color.WHITE);n.addView(nb("⌂\nInício",v->home()),new LinearLayout.LayoutParams(0,d(60),1));n.addView(nb("▤\nProtocolos",v->protocols()),new LinearLayout.LayoutParams(0,d(60),1));n.addView(nb("◉\nAnálises",v->bio()),new LinearLayout.LayoutParams(0,d(60),1));n.addView(nb("▦\nBiblioteca",v->library()),new LinearLayout.LayoutParams(0,d(60),1));return n;}
    Button nb(String s,View.OnClickListener l){Button x=new Button(a);x.setText(s);x.setTextSize(10);x.setTextColor(G);x.setAllCaps(false);x.setBackgroundColor(Color.WHITE);x.setOnClickListener(l);return x;}
    void splash(){LinearLayout p=new LinearLayout(a);p.setOrientation(LinearLayout.VERTICAL);p.setGravity(Gravity.CENTER);p.setBackgroundColor(Color.rgb(244,250,247));TextView logo=t("✦",46,true);logo.setTextColor(Color.WHITE);logo.setGravity(Gravity.CENTER);logo.setBackground(sh(G,30));p.addView(logo,new LinearLayout.LayoutParams(d(96),d(96)));p.addView(t("Integra Smart",30,true));p.addView(m("Plataforma Inteligente de Saúde Integrativa"));a.setContentView(p);}
    LinearLayout feature(String icon,String title,String desc,String action,View.OnClickListener l){LinearLayout c=card();c.addView(t(icon,29,false));c.addView(t(title,18,true));c.addView(m(desc));c.addView(b(action,l));return c;}
    void home(){LinearLayout p=page("Olá, profissional 👋","O que você deseja fazer hoje?");LinearLayout h=card();h.setBackground(sh(G,24));TextView x=t("Saúde + tecnologia + organização",22,true);x.setTextColor(Color.WHITE);h.addView(x);TextView y=m("Seu atendimento mais claro, simples e organizado.");y.setTextColor(Color.rgb(225,240,234));h.addView(y);p.addView(h);p.addView(feature("📋","Protocolos Inteligentes","Crie e organize protocolos de atendimento.","Criar protocolo",v->{step=1;create();}));p.addView(feature("🔎","Leitor de Biorressonância","Organize informações de relatórios em etapas.","Nova análise",v->bio()));p.addView(feature("📄","Relatório para Cliente","Monte uma apresentação clara e organizada.","Criar relatório",v->report()));p.addView(feature("📚","Biblioteca","Acesse protocolos, modelos e conteúdos.","Abrir biblioteca",v->library()));show(p);}
    void protocols(){LinearLayout p=page("Protocolos","Organize e desenvolva seus protocolos de atendimento.");p.addView(f("Buscar protocolo...",false));p.addView(chips(new String[]{"Todos","Dor","Sono","Bem-estar","Digestivo","Emocional","Circulação","Outros"}));p.addView(item("🌿","Protocolo de Bem-estar Geral","6 sessões · Hoje"));p.addView(item("🌙","Protocolo de Sono","5 sessões"));p.addView(item("🫧","Protocolo de Relaxamento","4 sessões"));p.addView(b("＋ Novo protocolo",v->{step=1;create();}));show(p);}
    View chips(String[] ss){HorizontalScrollView h=new HorizontalScrollView(a);h.setHorizontalScrollBarEnabled(false);LinearLayout r=new LinearLayout(a);r.setOrientation(LinearLayout.HORIZONTAL);for(String s:ss){Button x=alt(s,v->{});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,d(44));p.setMargins(0,d(6),d(6),d(6));x.setLayoutParams(p);r.addView(x);}h.addView(r);return h;}
    LinearLayout item(String icon,String title,String meta){LinearLayout c=card();c.addView(t(icon+"  "+title,16,true));c.addView(m(meta));return c;}
    void create(){LinearLayout p=page("Criar Protocolo","Etapa "+step+" de 4");TextView dots=t(step==1?"● ○ ○ ○":step==2?"● ● ○ ○":step==3?"● ● ● ○":"● ● ● ●",20,true);dots.setTextColor(G2);p.addView(dots);if(step==1){p.addView(t("Etapa 1 — Objetivo",16,true));p.addView(f("Nome do protocolo",false));p.addView(f("Objetivo principal",false));p.addView(f("Descreva o que deseja trabalhar neste protocolo...",true));p.addView(b("Continuar",v->{step=2;create();}));}else if(step==2){p.addView(t("Etapa 2 — Recursos",16,true));for(String s:new String[]{"💆 Massoterapia","💡 Fotobiomodulação","👂 Auriculoterapia","🌿 Terapias integrativas","🫧 Relaxamento guiado","＋ Outros"})p.addView(alt(s,v->{}));p.addView(b("Continuar",v->{step=3;create();}));}else if(step==3){p.addView(t("Etapa 3 — Organização",16,true));p.addView(item("1","Sessão 1","Adicionar recurso · Adicionar observação"));p.addView(item("2","Sessão 2","Adicionar recurso · Adicionar observação"));p.addView(alt("＋ Adicionar sessão",v->{}));p.addView(b("Continuar",v->{step=4;create();}));}else{LinearLayout c=card();c.addView(t("Revisão do protocolo",18,true));c.addView(m("Objetivo definido · recursos selecionados · 2 sessões adicionadas. Conteúdo demonstrativo."));p.addView(c);p.addView(alt("Editar",v->{step=1;create();}));p.addView(b("Salvar protocolo",v->{}));}show(p);}
    void bio(){LinearLayout p=page("Leitor de Biorressonância","Organize informações de um relatório em etapas.");LinearLayout c=card();c.setGravity(Gravity.CENTER);c.addView(t("⬆️",34,false));c.addView(t("Enviar arquivo",18,true));c.addView(m("PDF, imagem ou documento"));p.addView(c);p.addView(f("Cole o texto do resultado aqui...",true));p.addView(b("Analisar conteúdo",v->processing()));LinearLayout n=card();n.setBackground(sh(SOFT,16));n.addView(m("Demonstração de organização de informações. Não substitui avaliação profissional ou diagnóstico."));p.addView(n);show(p);}
    void processing(){LinearLayout p=page("Analisando informações","Demonstração visual do futuro processamento.");for(String s:new String[]{"✓ Texto recebido","✓ Informações identificadas","● Organização por categorias","○ Resumo dos achados","○ Revisão profissional","○ Relatório final"}){TextView x=t(s,16,true);x.setPadding(d(5),d(11),0,d(11));p.addView(x);}p.addView(b("Ver resultado",v->result()));show(p);}
    void result(){LinearLayout p=page("Resultado da análise",null);p.addView(item("🧾","Resumo geral","Conteúdo fictício, organizado sem diagnóstico."));p.addView(chips(new String[]{"Digestivo","Sono","Bem-estar","Circulação","Emocional"}));p.addView(item("A","Item demonstrativo","Resultado: 72 · Referência: 60–85 · Dentro da faixa"));p.addView(item("B","Item demonstrativo","Resultado: 48 · Referência: 50–75 · Atenção"));p.addView(item("C","Item demonstrativo","Resultado: 91 · Referência: 45–80 · Fora da faixa informada"));p.addView(b("Gerar relatório para cliente",v->report()));p.addView(alt("Revisar informações",v->{}));show(p);}
    void report(){LinearLayout p=page("Relatório para Cliente","Configure uma prévia visual.");p.addView(chips(new String[]{"Resumo simples","Relatório completo","Acompanhamento"}));p.addView(f("Nome do cliente",false));EditText date=f("Data",false);date.setText("13/08/2026");p.addView(date);p.addView(f("Título do relatório",false));p.addView(f("Observações profissionais",true));for(String s:new String[]{"✓ Incluir resumo","✓ Incluir categorias","✓ Incluir pontos destacados","✓ Incluir orientações gerais","✓ Incluir observações profissionais"})p.addView(alt(s,v->{}));p.addView(b("Visualizar relatório",v->preview()));show(p);}
    void preview(){LinearLayout p=page("Prévia do Relatório",null);LinearLayout c=card();c.addView(t("✦ Integra Smart",20,true));c.addView(m("Relatório de Saúde Integrativa · Nome do cliente · 13/08/2026"));for(String[] s:new String[][]{{"Resumo","Conteúdo demonstrativo organizado de forma clara."},{"Informações organizadas","Área destinada às informações do documento."},{"Pontos de atenção","Destaques sem apresentação de diagnóstico."},{"Observações do profissional","Espaço reservado para revisão profissional."},{"Orientações gerais","Área visual para orientações gerais."}}){c.addView(t(s[0],15,true));c.addView(m(s[1]));}c.addView(m("Este material possui caráter informativo e não substitui avaliação ou diagnóstico médico."));p.addView(c);p.addView(alt("Editar",v->report()));p.addView(b("Gerar PDF",v->{}));p.addView(alt("Compartilhar",v->{}));show(p);}
    void library(){LinearLayout p=page("Biblioteca","Seus materiais organizados em um só lugar.");p.addView(chips(new String[]{"Protocolos","Relatórios","Modelos","Conteúdos"}));p.addView(f("Pesquisar na biblioteca...",false));p.addView(item("📋","Bem-estar Geral","Protocolo · Hoje"));p.addView(item("📄","Modelo de relatório simples","Modelo · 12 ago"));p.addView(item("🌿","Conteúdo de apoio","Conteúdo · 10 ago"));show(p);}
}
