plugins {
    id 'com.android.application'
}

android {
    namespace 'com.livresparaadorar.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.livresparaadorar.app'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '4.0.0-test'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
